= Pizza Factory policy

== Phases

[cols="4*", options="header"]
|===
^|onRequest
^|onResponse
^|onMessageRequest
^|onMessageResponse

^.^| X
^.^| X
^.^|
^.^|
|===

== Description

You can use the `pizza` policy to create a pizza from request or response headers.

The headers having the form `X-Pizza-#key#: #value#` will be considered as valid headers to create the pizza.

`#key#` is a limited set of value which can be: `crust`, `sauce` and `topping`. (insensitive case). You need at least one header by category.
`#value#` is anything you want.

If no header starting with `X-Pizza-` can be found, then no pizza object will be created in the content of the request or response.

If content is not empty, a `pizza` object will be added. If there is no content, then the object will be created as root object.
We assume the content type will be `application/json`.

== Configuration

You can configure the policy with the following options:

[cols="5*", options=header]
|===
^| Property
^| Required
^| Description
^| Type
^| Default

.^|required
^.^|
.^|The list of required toppings.
^.^|array
^.^|

.^|forbidden
^.^|
.^|The list of forbidden toppings.
^.^|array
|

.^|pineappleForbidden
^.^|
.^|Is pineapple forbidden. Ends in a `406 - Not Acceptable` if "pineapple" is found in the toppings.
^.^|boolean
^.^|`true`

|===

Example configuration:

[source, json]
----
{
    "pizza-factory": {
        "required": ["sausage", "cheddar"],
        "forbidden": ["tuna"],
        "pineappleForbidden": true
    }
}
----

== Examples

For this input:

[source, json]
.Input
----
{
    "name": "My pizza"
}
----

[source, httprequest]
.Input
----
X-Pizza-Crust: Soft Pan
X-Pizza-Sauce: Tomato
X-Pizza-Topping: Mushroom
X-Pizza-Topping: Onions
X-Pizza-Topping: Ham
----

The output is as follows:

[source, json]
----
{
    "name": "My pizza",
    "pizza": {
      "crust": "Soft Pan",
      "sauce": "Tomato",
      "toppings": ["Mushroom", "Onions", "Ham"]
    }
}
----

== Errors

|===
|Phase | Code | Error template key | Description

.^| *
.^| ```406```
.^| NOT_ACCEPTABLE_PINEAPPLE
.^| Not Acceptable to have pineapple on a Pizza.

|===
